ae-recruitment-exercise1:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox1
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise2:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox2
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise3:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox3
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise4:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox4
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise5:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox5
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise6:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox6
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise7:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox7
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise8:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox8
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise9:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox9
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise10:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox10
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise11:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox11
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise12:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox12
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise13:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox13
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise14:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox14
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise15:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox15
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise16:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox16
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise17:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox17
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise18:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox18
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise19:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox19
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1


ae-recruitment-exercise20:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-recruitment-sandbox
      dataset: dbt_sandbox20
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast1
      priority: interactive
      retries: 1
